version: '3.8'

services:
  api:
    build: .
    container_name: backend-test-task
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"
